import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

const DraftLists: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>YGO Draft Cube</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="/">Draft List</a>
                </h1>
            </main>

            <footer className={styles.footer}>

            </footer>
        </div>
    )
}

export default DraftLists
