import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>YGO Draft Cube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="/">YGO Draft Cube</a>
        </h1>

        <p className={styles.description}>

        </p>

        <div className={styles.grid}>
          <a href="/draft-lists" className={styles.card}>
            <h2>Draft Lists &rarr;</h2>
            <p>Something something Dark Draft Lists Side</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export default Home
